/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.quickcougar.smart_fridge

import groovyx.net.http.RESTClient
import spock.lang.Shared
import spock.lang.Specification

class AppTest extends Specification {
    @Shared
    RESTClient client = new RESTClient('http://localhost/smart_fridge/')

//    def 'simple status checker'() {
//        when:
//        def response = client.get(path: 'status')
//
//        then:
//        with(response) {
//            data.text == 'Welcome to the Smart Fridge Service!'
//            status == 200
//        }
//    }
}
